// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: api.proto

package questionspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// QuestionsServiceClient is the client API for QuestionsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuestionsServiceClient interface {
	CreateQuestion(ctx context.Context, in *CreateQuestionRequest, opts ...grpc.CallOption) (*CreateQuestionResponse, error)
}

type questionsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQuestionsServiceClient(cc grpc.ClientConnInterface) QuestionsServiceClient {
	return &questionsServiceClient{cc}
}

func (c *questionsServiceClient) CreateQuestion(ctx context.Context, in *CreateQuestionRequest, opts ...grpc.CallOption) (*CreateQuestionResponse, error) {
	out := new(CreateQuestionResponse)
	err := c.cc.Invoke(ctx, "/questionspb.QuestionsService/CreateQuestion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuestionsServiceServer is the server API for QuestionsService service.
// All implementations must embed UnimplementedQuestionsServiceServer
// for forward compatibility
type QuestionsServiceServer interface {
	CreateQuestion(context.Context, *CreateQuestionRequest) (*CreateQuestionResponse, error)
	mustEmbedUnimplementedQuestionsServiceServer()
}

// UnimplementedQuestionsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedQuestionsServiceServer struct {
}

func (UnimplementedQuestionsServiceServer) CreateQuestion(context.Context, *CreateQuestionRequest) (*CreateQuestionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateQuestion not implemented")
}
func (UnimplementedQuestionsServiceServer) mustEmbedUnimplementedQuestionsServiceServer() {}

// UnsafeQuestionsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuestionsServiceServer will
// result in compilation errors.
type UnsafeQuestionsServiceServer interface {
	mustEmbedUnimplementedQuestionsServiceServer()
}

func RegisterQuestionsServiceServer(s grpc.ServiceRegistrar, srv QuestionsServiceServer) {
	s.RegisterService(&QuestionsService_ServiceDesc, srv)
}

func _QuestionsService_CreateQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateQuestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionsServiceServer).CreateQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/questionspb.QuestionsService/CreateQuestion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionsServiceServer).CreateQuestion(ctx, req.(*CreateQuestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QuestionsService_ServiceDesc is the grpc.ServiceDesc for QuestionsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuestionsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "questionspb.QuestionsService",
	HandlerType: (*QuestionsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateQuestion",
			Handler:    _QuestionsService_CreateQuestion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
