openapiOptions:
  file:
    - file: "questionspb/messages.proto"
      option:
        info:
          title: Questions
          version: "1.0.0"
        basePath: /
  method:
    - method: questionspb.QuestionsService.CreateQuestion
      option:
        operationId: createQuestion
        tags:
          - Question
        summary: Create a new question
        
    - method: questionspb.QuestionsService.GetQuestion
      option:
        operationId: getQuestion
        tags:
          - Question
        summary: Get a question by id